CREATE TABLE "conversation_followers" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "conversation_followers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"conversation_id" bigint NOT NULL,
	"user_id" uuid NOT NULL,
	CONSTRAINT "conversation_followers_conversation_user_unique" UNIQUE("conversation_id","user_id")
);
--> statement-breakpoint
ALTER TABLE "conversation_followers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE INDEX "conversation_followers_conversation_id_idx" ON "conversation_followers" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX "conversation_followers_user_id_idx" ON "conversation_followers" USING btree ("user_id");