CREATE TABLE "stored_tools" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stored_tools_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"customer_email" text,
	"description" text,
	"parameters" jsonb DEFAULT '[]' NOT NULL,
	"server_request_url" text
);
--> statement-breakpoint
ALTER TABLE "stored_tools" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE UNIQUE INDEX "unique_tool_idx" ON "stored_tools" USING btree ("name","customer_email");--> statement-breakpoint
CREATE INDEX "idx_stored_tools_customer_email" ON "stored_tools" USING btree ("customer_email") WHERE "stored_tools"."customer_email" IS NOT NULL;